# Use root/example as user/password credentials
version: '3.4'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    # network_mode: host
    volumes:
      - ./mysql/:/var/lib/mysql
      - ./sqlconf/:/etc/mysql/conf.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db" 
    # ports:
    #   - 8000:8000
    network_mode: host
    volumes: 
      - ./upload_files:/app/cow-app/upload_files
      - ./result_files:/app/cow-app/result_files
      - ./log:/app/cow-app/log
